//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyProduct("Cake.IIS")]
[assembly: AssemblyVersion("0.1.4")]
[assembly: AssemblyFileVersion("0.1.4")]
[assembly: AssemblyInformationalVersion("0.1.4")]
[assembly: AssemblyCopyright("Copyright (c) Sergio Silveira, Phillip Sharpe 2015")]

